screen=CLOUD_FOG_END
screen.columns=1

sliders=CLOUD_FOG_END

oldHandLight=false
underwaterOverlay=true
vignette=true
oldLighting=true
separateEntityDraws=true
allowConcurrentCompute=true
particles.ordering=mixed
shadow.enable=false

iris.features.required=ENTITY_TRANSLUCENT
iris.features.optional=FADE_VARIABLE

blend.gbuffers_skybasic=off
blend.gbuffers_basic=off
blend.gbuffers_beaconbeam=off
blend.gbuffers_block=off
blend.gbuffers_damagedblock=off
blend.gbuffers_entities=off
blend.gbuffers_hand=off
blend.gbuffers_particles=off
blend.gbuffers_skybasic=off
blend.gbuffers_spidereyes=off
blend.gbuffers_terrain_cutout=off
blend.gbuffers_terrain_solid=off
blend.gbuffers_terrain=off
blend.gbuffers_textured_lit=off

blend.gbuffers_block_translucent=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_clouds=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_entities_translucent=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_hand_water=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_lightning=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_line=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_particles_translucent=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_textured=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_water=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_weather=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA

blend.gbuffers_armor_glint=ONE ONE ZERO ONE

blend.gbuffers_skytextured=ONE ONE ZERO ZERO

blend.shadow=off
blend.shadow_block=off
blend.shadow_cutout=off
blend.shadow_entities=off
blend.shadow_solid=off
blend.shadow_water=off

blend.dh_shadow=off
blend.dh_terrain=off
blend.dh_water=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
